### ISSUE TITLE
BUG: 'All' button when clicked won't open the other day buttons in Price Chart

### ISSUE THREAD

**Issue by mariarabin** [ayang726/Project-2#10]
once you clicked 'ALL' - the succeeding day button clicks will re-open the 'ALL' transactions (like when you clicked 1-Day after ALL ...1-Day will open ALL Transactions)

**Comment by alexjzyang** [comment]
This is found to be a bug when loading the data array. Because the data array is not cleared upon loading new data, additional data are just pushed to the array and rendered on the chart.

**Comment by mariarabin** [comment]
Fix is under https://github.com/ayang726/Project-2/pull/19
