### ISSUE TITLE
Less data points for charts

### ISSUE THREAD

**Issue by alexjzyang** [ayang726/Project-2#30]
We need to eliminate some data points from the plots,  and not plotting all the data on the chart.

**Comment by mariarabin** [comment]
@ayang726  hi! I have made 'max' to now be just '5y'. Let me know of this can be closed or not. Thanks!

**Comment by mariarabin** [comment]
Pull 1 point and add this one point to the chart for the 5 minute refresh

**Comment by mariarabin** [comment]
Fix was on https://github.com/ayang726/Project-2/pull/50
