### ISSUE TITLE
Root page going directly to the home page when localhost:7000 is opened

### ISSUE THREAD

**Issue by mariarabin** [ayang726/Project-2#9]
When you typed in localhost:7000 - it changes to localhost:7000/home

**Comment by alexjzyang** [comment]
This is not a bug, but a feature. If you're logged in, the browser remembers it and redirect you to the home page. If you log out, you will see the root/login page

**Comment by mariarabin** [comment]
I tried logging in but logout doesn't work.

**Comment by alexjzyang** [comment]
updating from iframe to canvas within the stockView section should fix this issue.

**Comment by mariarabin** [comment]
this is fixed now right? wondering why you reopened
